message_type: FilterJointTrajectory
filter_chain:
  - 
    name: unnormalize_trajectory
    type: UnNormalizeTrajectory
  -
    name: cubic_spline_short_cutter_smoother
    type: CubicSplineShortCutter


