service_type: FilterJointTrajectoryWithConstraints
filter_chain:
  - 
    name: unnormalize_trajectory
    type: UnNormalizeFilterJointTrajectoryWithConstraintsRequest
  -
    name: cubic_spline_short_cutter_smoother
    type: CubicSplineShortCutterFilterJointTrajectoryWithConstraintsRequest
    params: {discretization: 0.01}
